# Generated by Django 3.0.6 on 2020-05-13 21:40

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(events.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
