version: '3'
services:

  web:
    build: .
    volumes:
        - .:/code
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0:8000"
